title:              DigiSci
email:              pranavkishan@outlook.com  
description:        A blog run by Sai Pranav Kishan. Welcome!
author:             Sai Pranav Kishan
baseurl:            "/blog"
url:                "https://pranavkishan213.github.io"

# Social Profiles
twitter_username:   kishan_pranav
github_username:    PranavKishan213
facebook_username: 
instagram_username:  kishanpranav
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
